# Yuri Fonseca Lopes - 214450006

# 1. Formaliza√ß√£o do problema

Existem v√°rias maneiras de avaliar o desempenho de uma empresa para decidir se √© v√°lido comprar a√ß√µes da mesma. Alguns m√©todos existentes s√£o:

CAPM (Modelo de precifica√ß√£o de ativos de capital). √â um m√©todo que analise a rela√ß√£o entre o risco e o retorno que √© esperado de um investimento, obtido a partir de princ√≠pios de diversifica√ß√£o com pressupostos simplificados.

HME (Hip√≥tese do mercado eficiente). Essa hip√≥tese afirma que os mercados s√£o eficientes, ou seja, um agente n√£o consegue alcan√ßar consistentemente retornos superioers √† m√©dia do mercado, pois os pre√ßos dos ativos refletem toda a informa√ß√£o dispon√≠vel em um dado momento de tempo.

An√°lise t√©cnica. √â uma busca por padr√µes recorrentes e previs√≠veis nos pre√ßos do ativo.

An√°lise Fundamentalista. Utiliza indicadores financeiros, de gest√£o, do neg√≥cio e do risco da empresa, al√©m de √≠ndices macroecon√¥micos na busca de determinar o valor presente descontado dos fluxos de caixa da empresa para chegar ao valor justo de cada a√ß√£o.

# 2. Mudan√ßas em rela√ß√£o ao TP1

No TP1, eu mapeei os √çndices de Governan√ßa para valores num√©ricos e apliquei o K-means nesses novos valores somados. Nesse trabalho n√£o irei realizar essa soma, irei inserir todos os 54 √çndices de Govern√ßa. Por conta disso, urei usar redu√ß√£o de dimensionalidade para visualiza√ß√£o dos clusters.

Fiz uma revis√£o na literatura (pesquisei assuntos internacionais) que acabou comprovando uma ideia (no meio das milhoes que eu tinha) que eu tive no TP1. Empresas que n√£o pontuam bem no Social e Ambiental (Social and Enviromental) e pontuaram bem em Governan√ßa acabam tendo rendimentos maiores que as demais. Fonte: https://www.sciencedirect.com/science/article/pii/S221484502200093X

Esse trabalho citado usou clusteriza√ß√£o com o Kmeans++ na bolsa da Turquia. Vou tentar preparar o ambiente para fazer o mesmo aqui com a Bolsa Brasileira. Contudo, terei que adquirir novos dados, pois a base de dados ainda n√£o conta com o rendimento (e outros indicadores de empresas). O trabalho citado usou uma base de dados paga üòí

Essa nova abordagem continua sendo relevante, pois possibilita a identifica√ß√£o de Indices de Governan√ßa espec√≠ficos que indicam bons rendimentos. Com esse novo conhecimento, podemos por exemplo identificar uma empresa que ir√° realizar um IPO e prever o rendimento dela com base nos poss√≠veis √≠ndices que a mesma ir√° cumprir durante o tempo.

# 3. An√°lise explorat√≥ria de dados (EDA)

In [9]:
# @title Importando os pacotes necess√°rios

import pandas as pd
import requests
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
from matplotlib import pyplot as plt
import plotly.express as px

In [2]:
# @title Carregando o dataset

# URL do arquivo CSV
url = 'https://github.com/Yurovskyy/CDD/raw/main/dataset_CGVN.csv'

# Baixar o arquivo CSV da web
response = requests.get(url)

# Verificar se a solicita√ß√£o foi bem-sucedida
if response.status_code == 200:
    # Ler o conte√∫do do arquivo CSV usando o Pandas
    df = pd.read_csv(url)

# Se a solicita√ß√£o n√£o for bem-sucedida
else:
    print('Falha ao baixar o arquivo CSV.')

# Obter as dimens√µes do DataFrame

In [3]:

# @title Explora√ß√£o inicial do dataset

dimensoes = df.shape
print("N√∫mero de entradas(linhas):", dimensoes[0])
print("N√∫mero de colunas(vari√°veis):", dimensoes[1])

# identificar o tipo de cada vari√°vel
display(df.dtypes)

# ver as 5 primeiras entradas do conjunto de treino
display(df.head())

N√∫mero de entradas(linhas): 115722
N√∫mero de colunas(vari√°veis): 5

Data_Referencia     object
Versao               int64
Nome_Empresarial    object
ID_Item             object
Pratica_Adotada     object
dtype: object

  Data_Referencia  Versao Nome_Empresarial ID_Item Pratica_Adotada
0      2018-12-31       1  BCO BRASIL S.A.   1.1.1             Sim
1      2018-12-31       1  BCO BRASIL S.A.   1.2.1             Sim
2      2018-12-31       1  BCO BRASIL S.A.   1.3.1             Sim
3      2018-12-31       1  BCO BRASIL S.A.   1.3.2             Sim
4      2018-12-31       1  BCO BRASIL S.A.   1.4.1             N√£o

In [4]:
# @title Valores faltantes
# @markdown Como eu disso, n√£o temos valores faltantes!

# ver a porcentagem valores faltantes
display((df.isnull().sum() / df.shape[0]).sort_values(ascending=False))

Data_Referencia     0.0
Versao              0.0
Nome_Empresarial    0.0
ID_Item             0.0
Pratica_Adotada     0.0
dtype: float64

In [5]:
# @title Descri√ß√£o dos valores categ√≥ricos
# @markdown Temos 499 empresas √∫nicas! (contando com as que se repetem em diferentes intervalos de tempo)

display(df.describe(include=['O']))

       Data_Referencia Nome_Empresarial ID_Item Pratica_Adotada
count           115722           115722  115722          115722
unique              34              499      54               4
top         2022-12-31      GERDAU S.A.   1.1.1             Sim
freq             23004              378    2143           60208

In [6]:
# @title Transforma√ß√£o das vari√°veis categ√≥rias em num√©ricas
# @markdown Vamos definir PAN como Pr√°ticas Adotadas Num√©ricas

# Criar um dicion√°rio de mapeamento
mapeamento = {
    'Sim': 0.5,
    'N√£o': -1,
    'N√£o se Aplica': -0.5,
    'Parcialmente': 0
}

# Usar o m√©todo map() para aplicar o mapeamento √† coluna
df['PAN'] = df['Pratica_Adotada'].map(mapeamento)

# Exibir o DataFrame com a nova coluna
display(df)

,Data_Referencia,Versao,Nome_Empresarial,ID_Item,Pratica_Adotada,PAN
0,2018-12-31,1,BCO BRASIL S.A.,1.1.1,Sim,0.5
1,2018-12-31,1,BCO BRASIL S.A.,1.2.1,Sim,0.5
2,2018-12-31,1,BCO BRASIL S.A.,1.3.1,Sim,0.5
3,2018-12-31,1,BCO BRASIL S.A.,1.3.2,Sim,0.5
4,2018-12-31,1,BCO BRASIL S.A.,1.4.1,N√£o,-1.0
...,...,...,...,...,...,...
115717,2024-12-31,1,METALURGICA GERDAU S.A.,5.3.2,Sim,0.5
115718,2024-12-31,1,METALURGICA GERDAU S.A.,5.4.1,Sim,0.5
115719,2024-12-31,1,METALURGICA GERDAU S.A.,5.5.1,Sim,0.5
115720,2024-12-31,1,METALURGICA GERDAU S.A.,5.5.2,Sim,0.5
115721,2024-12-31,1,METALURGICA GERDAU S.A.,5.5.3,N√£o se Aplica,-0.5

In [15]:

# X = soma_por_empresa['PAN']
df2 = df
colunas = ['Data_Referencia','Nome_Empresarial','ID_Item','PAN']
X = df2[colunas]
# print(X)

# Transformar data de character para Date
df2['Data_Referencia'] = pd.to_datetime(df2['Data_Referencia'], format='%Y-%m-%d')

# Selecionar colunas relevantes para a clusteriza√ß√£o
columns_to_use = ['Data_Referencia', 'Nome_Empresarial', 'ID_Item', 'PAN']

# Filtrar o DataFrame
df2 = df2[columns_to_use]

print(df2)

# Criar transforma√ß√µes para colunas categ√≥ricas e num√©ricas
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['PAN']),
        ('cat', OneHotEncoder(sparse_output=False), ['Nome_Empresarial', 'ID_Item'])
    ],
    remainder='passthrough'  # Manter a coluna de data
)

# Aplicar as transforma√ß√µes e obter o array transformado
transformed_data = preprocessor.fit_transform(df2)

# Nomear as colunas resultantes das transforma√ß√µes
one_hot_columns = preprocessor.named_transformers_['cat'].get_feature_names_out(['Nome_Empresarial', 'ID_Item'])
numeric_columns = ['PAN']
date_columns = ['Data_Referencia']

# Concatenar todos os nomes de colunas
all_columns = list(one_hot_columns) + numeric_columns + date_columns

# Criar DataFrame transformado
df_transformed = pd.DataFrame(transformed_data, columns=all_columns)

# Visualizar o DataFrame transformado
print(df_transformed.head())

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Float64DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.DateTime64DType'>)